### ISSUE TITLE
마우스 커서 관련 이슈

### ISSUE THREAD

**Issue by happy-yeachan** [100-hours-a-week/2-jeonggu-kim-community-fe#24]
**버그 설명**
마우스 커서 위치와 파란 동그라미 위치가 달라짐

**재현하는 방법**
동작을 재현하는 단계:
1. 회원가입 창 진입
2. 이미지 선택
3. 이후 마우스 커서 위치 이상 현상 발생

**예상한 동작**
- 위 동작 후 파란 동그라미가 제 마우스인지 구름이 제 마우스인지 모르겠습니다.

**스크린샷**
![image](https://github.com/user-attachments/assets/3c280ab4-158b-4dad-8d84-dc63f28b4ba3)

**데스크톱(다음 정보를 작성해 주세요):**
 - chrome

**스마트폰(다음 정보를 입력하세요)**

**추가적인 내용**
여기에 문제에 대한 다른 컨텍스트를 추가해주세요.

**Comment by happy-yeachan** [comment]
아 파일을 첨부하는 동작이 아닌 그냥 스크롤을 하면 파란 동그라미도 같이 딸려가네요 ㅋㅋㅋㅋ

**Comment by dev-jeonggu** [comment]
현재 문제가 되는 부분은 마우스 커서가 원활하게 따라가지 못하면서 발생합니다. 이를 해결하기 위해서는 마우스 움직임을 더욱 세밀하게 체크해야 하지만, 프론트엔드 페이지에서 이를 구현하는 것은 비효율적이라고 판단했습니다.
따라서 해당 동그라미 요소를 제거하는 방향으로 수정하겠습니다.
