### ISSUE TITLE
게시글 이미지 수정이 되지않는 이슈

### ISSUE THREAD

**Issue by happy-yeachan** [100-hours-a-week/2-jeonggu-kim-community-fe#31]
**버그 설명**
게시글 이미지 수정이 되지 않습니다.

**재현하는 방법**
동작을 재현하는 단계:
1. 게시글 수정 페이지 접근
2. 다른 이미지 업로드
3. 수정완료

**예상한 동작**
수정된 이미지로 변경되어야 한다

**스크린샷**
문제를 설명하는 데 도움이 되는 스크린샷을 추가하세요. 스크린샷으로 어렵다면 영상첨부해주세요.

**데스크톱(다음 정보를 작성해 주세요):**

**스마트폰(다음 정보를 입력하세요)**

**추가적인 내용**
여기에 문제에 대한 다른 컨텍스트를 추가해주세요.

**Comment by dev-jeonggu** [comment]
해당 부분을 코드 통합하면서 이전 코드가 남아 있어서 발생한 부분입니다. 수정하겠습니다.
