### ISSUE TITLE
[윈도우-1440-로그인 페이지] 헤더 뒤로 가기 버튼 의미? (1회차)

### ISSUE THREAD

**Issue by gsandoo** [100-hours-a-week/2-jeonggu-kim-community-fe#39]
**버그 설명**
버그에 대한 명확하고 간결한 설명해주세요.

**재현하는 방법**
동작을 재현하는 단계:
1. Go to 로그인페이지
2. Click on 헤더 뒤로가기 버튼

**예상한 동작**
확실한 목적이 없다면 첫 렌더링 페이지에 뒤로 가기 버튼은 없어도 된다고 생각합니다.

**스크린샷**
![image](https://github.com/user-attachments/assets/3ffe1f73-3089-475a-9a5f-1b12c516f325)
![image](https://github.com/user-attachments/assets/64ee8778-5b76-4859-9095-f49fa8324ffc)

**추가적인 내용**
피그마에도 없기에 이슈 남겨봅니다. 커스터마이징을 의도하신 거라면 이슈 해소해도 됩니다

**Comment by dev-jeonggu** [comment]
해당 부분은 제가 추가를 제외하면서 누락된 것 같습니다. 수정하겠습니다.
