### ISSUE TITLE
[윈도우-1440-비밀번호 수정 페이지] 비밀 번호 수정이 안됨 (1회차)

### ISSUE THREAD

**Issue by gsandoo** [100-hours-a-week/2-jeonggu-kim-community-fe#40]
**버그 설명**
버그에 대한 명확하고 간결한 설명해주세요.

**재현하는 방법**
동작을 재현하는 단계:
1. Go to 비밀번호 수정 페이지
2. Type on 비밀번호

**예상한 동작**
비밀번호 수정이 안되는 이유가 궁금합니다. 비밀번호가 서로 다른 건지 버그 인 건지 helper text 주시면 좋을 것 같습니다. 

**스크린샷**
![image](https://github.com/user-attachments/assets/0e802cc2-7aa0-4f72-9b6f-af1a92c49a16)

**Comment by dev-jeonggu** [comment]
이건 제가 비밀번호 관련 기능 수정을 하다가 로직이 꼬인것 같습니다. 해당 부분은 수정하도록 하겠습니다.
