### ISSUE TITLE
[윈도우-1440-로그인페이지] Contact , About 버튼 페이지 렌더링 이슈 (1회차)

### ISSUE THREAD

**Issue by gsandoo** [100-hours-a-week/2-jeonggu-kim-community-fe#43]
**버그 설명**
Contact 버튼 -> 새로고침
About 버튼 -> 깃허브 be 이동

**재현하는 방법**
동작을 재현하는 단계:
1. Go to 로그인 페이지
3. Click on Contact , About 버튼

**예상한 동작**
Contact, About 버튼 클릭 시 해당 페이지로 이동하는 줄 알았습니다. 예상한 페이지 개발이 이루어지지 않았을 시 block 처리 하면 좋을 것 같습니다.

**스크린샷**
![image](https://github.com/user-attachments/assets/2b39d982-156a-4729-8251-723c470d9429)

**추가적인 내용**
여기에 문제에 대한 다른 컨텍스트를 추가해주세요.

**Comment by dev-jeonggu** [comment]
해당 부분은 각각 연결 하려고 하다가 일단 제외해둔 부분인데 해당 부분을 추가해서 연결하도록 하겠습니다.
