### ISSUE TITLE
 [MacOS-Chrome-1920px-게시글 수정] 게시글이 수정된 시간이 업데이트 되지 않습니다.

### ISSUE THREAD

**Issue by gmlwlsdl** [100-hours-a-week/2-jeonggu-kim-community-fe#47]
**버그 설명**
게시글이 수정된 시간이 업데이트 되지 않습니다.

**재현하는 방법**
동작을 재현하는 단계:
1. 게시글을 수정한다.
2. 수정한 시간으로 게시글 시간 정보가 업데이트 된다.

**예상한 동작**
예상했던 일에 대한 명확하고 간결한 설명해주세요.

**스크린샷**
![무제](https://github.com/user-attachments/assets/3c1dade1-58f9-4660-9c18-9f0bf1e13a0c)

**데스크톱(다음 정보를 작성해 주세요):**
 - OS: MacOS
 - Browser: Chrome
 - Version: 131.0.6778.109(공식 빌드) (arm64)

**Comment by gmlwlsdl** [comment]
댓글 수정 시간도 업데이트 되지 않고 있습니당 🔥
![무제](https://github.com/user-attachments/assets/32e2973a-8041-45b8-9c07-82afdade61eb)

**Comment by dev-jeonggu** [comment]
해당 부분은 작성한 시간을 기준으로 노출이 됩니다. 최초 작성된 시간이 노출되어야 한다고 생각을 해서 대신 수정된 내용은 (수정됨) 이라는 내용을 추가하겠습니다.
