### ISSUE TITLE
 [MacOS-Chrome-1920px-게시글 상세] 게시글 상세 페이지에서 게시글 수정 페이지로 이동합니다.

### ISSUE THREAD

**Issue by gmlwlsdl** [100-hours-a-week/2-jeonggu-kim-community-fe#50]
**버그 설명**
게시글 수정 후, 게시글 상세 페이지에서 뒤로 가기 버튼 클릭시 게시글 수정 페이지로 이동합니다.

**재현하는 방법**
동작을 재현하는 단계:
1. 게시글을 수정한다.
2. 수정된 게시글 상세 페이지에서 뒤로 가기 버튼을 클릭한다.

**예상한 동작**
게시글 목록을 보여주는 페이지로 이동한다.

**스크린샷**
![무제](https://github.com/user-attachments/assets/2838a08b-f203-4d26-9659-57187ce3dee4)

**데스크톱(다음 정보를 작성해 주세요):**
 - OS: MacOS
 - Browser: Chrome
 - Version: 131.0.6778.109(공식 빌드) (arm64)

**추가적인 내용**
혹시 `-1`로 뒤로 가기 버튼이 구현되어 있나요?? 명시적으로 페이지의 path를 이용해서 이동하는 로직을 이용해 주시면 해결될 거 같습니다! 👍🏻🔥

**Comment by dev-jeonggu** [comment]
이 부분은 이전 이슈 란에 말씀드린대로, 해당 버튼은 뒤로가기 버튼으로 window.history.back();이 적용됩니다. 어떤 작업을 하든 이전 페이지로 돌아가는 부분인데, 페이지마다 경로를 지정할지 고려해보겠습니다.
