### ISSUE TITLE
[윈도우-1440-회원가입페이지] 프로필 이미지 재업로드 클릭 시 동작 안함 이슈

### ISSUE THREAD

**Issue by gsandoo** [100-hours-a-week/2-jeonggu-kim-community-fe#53]
**버그 설명**
버그에 대한 명확하고 간결한 설명해주세요.

**재현하는 방법**
동작을 재현하는 단계:
1. Go to 회원가입 페이지
2. Click on 프로필 이미지
3. 다시 프로필 이미지 재업로드

**예상한 동작**
프로필 이미지 재 업로드 시 동작을 하지 않습니다.

**스크린샷**
![image](https://github.com/user-attachments/assets/5b9d8eb5-361a-4c56-84b9-eae74e689eae)

**Comment by dev-jeonggu** [comment]
@gsandoo  해당 버튼의 존재가 이미지 업로드 후, 다시 재 등록을 하고 싶을 때 초기화 하는 용도의 버튼인데, 버튼 명이 애매한 것 같습니다. 버튼 명을 바꾸겠습니다. 추천 있으시다면 말씀해주세요.

**Comment by gsandoo** [comment]
프로필 이미지 초기화가 좋겠군요!
