### ISSUE TITLE
 [MacOS-Chrome-1920px-헤더 CSS] 헤더의 CSS가 공통되지 않습니다.

### ISSUE THREAD

**Issue by gmlwlsdl** [100-hours-a-week/2-jeonggu-kim-community-fe#55]
**버그 설명**
헤더의 CSS가 공통되지 않습니다.

**스크린샷**
|게시글 조회 페이지 헤더|회원 정보 페이지 헤더|
|:---:|:---:|
|![image](https://github.com/user-attachments/assets/a41d9ef6-f722-413e-aadc-b822dab845e3)|![image](https://github.com/user-attachments/assets/e10a67ec-cfd3-4fb8-b8d1-6f4925c81ffe)|

**데스크톱(다음 정보를 작성해 주세요):**
 - OS: MacOS
 - Browser: Chrome
 - Version: 131.0.6778.109(공식 빌드) (arm64)

**Comment by dev-jeonggu** [comment]
해당 부분은 공용이 맞으나 각각의 페이지마다 width가 다르게 설정해 놨습니다. 이것은 의도적으로 그렇게 해둔 것으로... 따로 수정할 부분은 없다고 판단이 되는데, 보기 불편하시다면 가로 width를 동일하게 고정하겠습니다.
