### ISSUE TITLE
 [MacOS-Chrome-1920px-게시글 조회 페이지] body, main 영역이 바르게 잡혀있지 않습니다.

### ISSUE THREAD

**Issue by gmlwlsdl** [100-hours-a-week/2-jeonggu-kim-community-fe#57]
**버그 설명**
body, main 영역이 바르게 잡혀있지 않습니다.

**스크린샷**
|body|main|
|:---:|:---:|
|![image](https://github.com/user-attachments/assets/688e1d82-18a0-462e-9be4-6d8dc592530b)|![image](https://github.com/user-attachments/assets/8f9832af-7bf6-46f2-bdd1-bbe46cf2c504)|

**데스크톱(다음 정보를 작성해 주세요):**
 - OS: MacOS
 - Browser: Chrome
 - Version: 131.0.6778.109(공식 빌드) (arm64)

**Comment by dev-jeonggu** [comment]
안에 코드들을 묶는 용도로 사용했을 뿐 영역까지 다루어야 한다고 생각해본 적은 없는데, 해당 부분은 추후에 고려해보겠습니다.
